site_name: Apuntes de PyTorch y Redes Neuronales
site_description: Apuntes de PyTorch y Redes Neuronales

# repo_url: https://github.com/fernandocarazomelo/pytorch-deep-learning-es/
# repo_name: fernandocarazomelo/pytorch-deep-learning-es

theme:
  name: material
  logo: assets/iconp.png
  favicon: assets/iconp.png
  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

site_url: "https://fernandocarazomelo.github.io/pytorch-deep-learning-es/"

nav:
  - Home: 'index.md'
  - 01. Introducción a PyTorch. Tensores y Gradientes: '01_pytorch_fundamentals_es.ipynb'
  - 02. Redes Neuronales en PyTorch: '02_pytorch_linear_regression_es.ipynb'
  - 03. Clasificación de Imágenes con PyTorch: '03_pytorch_logistic_regression_es.ipynb'
  
  # - 04. Conjuntos de Datos Personalizados con PyTorch: '04_pytorch_custom_datasets_es.ipynb'
  # - 06. Aprendizaje por Transferencia con PyTorch: '06_pytorch_transfer_learning_es.ipynb'
  # - 07. Seguimiento de Experimentos con PyTorch: '07_pytorch_experiment_tracking_es.ipynb'
  # - 08. Replicando Artículos de Investigación en Aprendizaje Automático con PyTorch: '08_pytorch_paper_replicating_es.ipynb'
  # - 09. Desplegando Modelos de Aprendizaje Automático con PyTorch: '09_pytorch_model_deployment_es.ipynb'

#   # - A Quick PyTorch 2 Tutorial: 'pytorch_2_intro.ipynb'
#   # - PyTorch Extra Resources: 'pytorch_extra_resources.md'
#   # - PyTorch Cheatsheet: 'pytorch_cheatsheet.ipynb'
#   # - Three Most Common PyTorch Errors: 'pytorch_most_common_errors.ipynb'
#   # - Test 00 as markdown: '00_pytorch_fundamentals.md'

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/fernandocarazo/
    - icon: fontawesome/brands/github 
      link: https://github.com/fernandocarazomelo